### ISSUE TITLE
GENERAL NOTE: "Warning: date_default_timezone_get()" Upon Installation

### ISSUE THREAD

**Issue by sajjadhossain** [knpuniversity/rest#30]
I personally used http://stackoverflow.com/a/26415168/4868653 to solve an error I saw causing the app to fail upon request. 

Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/EnderWiggin/Sites/trest/rest/vendor/monolog/monolog/src/Monolog/Logger.php on line 214

Is the initial error, but my date and time settings were also not set in `/etc/php.ini` on my Mac OS X. Lines `907-910`:

[Date]
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
; date.timezone = "America/New_York" (change value in quotes)

I usually keep a label named NOTES open in my github issues. JIC.

**Comment by sajjadhossain** [comment]
And to clear the above error I hacked in the below in line `14`

date_default_timezone_set('America/Los_Angeles');

**Comment by weaverryan** [comment]
Hi @sajjadhossain!

Yea, unfortunately this is a setup issue that *all* people using PHP will hit (at least once you start using more modern libraries, like Symfony or Silex) - PHP just doesn't set this setting for you, and complains when it's not set. It's one of the first things I run into when I give my trainings :).

Your above code will definitely work, but you should also be able to update it globally by uncommenting out the `date.timezone` setting in your `/etc/php.ini` file (you need to *remove* the semicolon - it is the comment character):

```ini
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = "America/New_York"
```

Once you've done that, restart your web-server (not necessary if you're using the built-in php web server). If that doesn't work, then it's likely that the PHP your web server is using is *not* the PHP whose INI file you just modified - this unfortunately happens on Mac OS X a lot - multiple installs of PHP.

Let me know if this helps - I'm not sure how to help people with this - it's just something you'll *always* hit exactly once when setting your system up.

Cheers!
