### ISSUE TITLE
ApiProblemExceptionListener

### ISSUE THREAD

**Issue by peterrehm** [knpuniversity/rest#37]
It might make sense to recommend to check in the ApiProblemExceptionListener that also
a route matches to prevent Json responses in the actual app if you have frontend and backend in the same app.
 
````php
class ApiProblemExceptionListener
{
    public function onKernelException(GetResponseForExceptionEvent $event)
    {
        $exception = $event->getException();

        // Skip if we are not in the API context
        if (strpos($event->getRequest()->getPathInfo(), '/api/') !== 0) {
            return;
        }

        if ($exception instanceof ApiProblemException) {
            $this->handleApiProblem($event, $exception->getApiProblem());
        }
}
````

**Comment by weaverryan** [comment]
Hey @peterrehm!

You're right of course :). But, I think this is actually already this way for the Symfony REST tutorial (I thought it wasn't at first, but it's here: http://knpuniversity.com/screencast/symfony-rest2/debugging-cleanup#fixing-web-errors). It's just mentioned a bit later than you might expect (why I missed it at first).

Does that look right to you? Either way, I appreciate you watching out for something like this :).

**Comment by peterrehm** [comment]
Oh awesome, I was not aware of that. I just purchased the rest tutorial in the past and I thought this will be a useful mention as I stumbled upon that issue recently :)

**Comment by weaverryan** [comment]
@peterrehm yea, it sounded like such a good idea to me too - that I started to add it.. then found that it was already added! So I too had forgotten it was there :). Cheers!
